### ISSUE TITLE
请问近期有考虑过在dashboard上加上回滚操作吗

### ISSUE THREAD

**Issue by snakeeeeeeeee** [eip-work/kuboard-press#161]
请问下,近期的版本有考虑在dashboard上加上回滚操作吗

**Comment by shaohq** [comment]
现在已经在 v1.0.8 中支持 Deployment 的回滚，请参考 https://kuboard.cn/learning/k8s-intermediate/workload/wl-deployment/rollback.html

**Comment by shaohq** [comment]
Resolved
