### ISSUE TITLE
请问下只读用户如何才能查看日志

### ISSUE THREAD

**Issue by bjddd192** [eip-work/kuboard-press#185]
使用v1.0.6.3版本部署后，发现只读用户也不能查看日志了，但是我希望可以支持。
之前用v1.0.4.1版本是可以支持只读用户查看日志的，这个是一个常用的功能，新版本要如何处理才能支持呢？谢谢

**Comment by shaohq** [comment]
请参考这篇文档  https://kuboard.cn/learning/k8s-advanced/sec/rbac/logs.html

**Comment by bjddd192** [comment]
好的，非常感谢大佬解答。

**Comment by shaohq** [comment]
请参考这个链接

https://kuboard.cn/learning/k8s-advanced/sec/rbac/logs.html <https://kuboard.cn/learning/k8s-advanced/sec/rbac/logs.html>
