### ISSUE TITLE
华为鲲鹏arm服务器上安装：standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by guomenghao** [eip-work/kuboard-press#190]

**Comment by shaohq** [comment]
已针对 arm 提供单独构建的镜像，请使用 镜像标签 eipwork/kuboard:arm

**Comment by githubzouzhiwei** [comment]
eipwork/kuboard找不到

**Comment by shaohq** [comment]
用这个镜像 eipwork/kuboard:arm 专门为arm服务器构建的镜像。发自我的华为手机-------- 原始邮件 --------发件人： githubzouzhiwei <notifications@github.com>日期： 2020年4月27日周一 10:18收件人： eip-work/kuboard-press <kuboard-press@noreply.github.com>抄送： shaohq <77128473@qq.com>, State change <state_change@noreply.github.com>主    题： Re: [eip-work/kuboard-press] 华为鲲鹏arm服务器上安装：standard_init_linux.go:211: exec user process caused "exec format error" (#190)

eipwork/kuboard找不到
