### ISSUE TITLE
名稱空間在使用創建按鈕時會改變成 example

### ISSUE THREAD

**Issue by sung1020** [eip-work/kuboard-press#195]
![image](https://user-images.githubusercontent.com/2267453/79547235-34723000-80c6-11ea-934c-5dccda090917.png)

kuboard: v1.0.9.1

**Comment by shaohq** [comment]
已确认此问题，将在 v1.0.9.3 中修复，预计4月19日发布

**Comment by shaohq** [comment]
已于 v1.0.9.3 中修复
