### ISSUE TITLE
安装资源监控套件失败

### ISSUE THREAD

**Issue by staneee** [eip-work/kuboard-press#251]
kuboard 安装资源监控套件， `prometheus-k8s` 跑不起来

报错  `pod has unbound immediate PersistentVolumeClaims.`

存储卷声明列表有 ` prometheus-k8s-db-prometheus-k8s` 存在

k8s版本为 `v1.20.1`

kuboard版本为 `v3.1.03`

Agent版本为 `v3.1.0`

**Comment by staneee** [comment]
![image](https://user-images.githubusercontent.com/26987099/116020083-2f03da00-a678-11eb-98a8-660772fa8ad6.png)

![image](https://user-images.githubusercontent.com/26987099/116020111-362ae800-a678-11eb-94d3-63a4b452d6b5.png)

![image](https://user-images.githubusercontent.com/26987099/116020127-3fb45000-a678-11eb-9ab0-95a1357be94f.png)

**Comment by 284330505** [comment]
我遇到了同样得问题，这个问题解决了吗

**Comment by staneee** [comment]
> 我遇到了同样得问题，这个问题解决了吗

它不支持普通的storage，需要配置nfs

**Comment by BraveSeeker** [comment]
我配置了nfs，说权限不足。服务器上把nfs目录的权限改成了777还是说权限不足，不知道问题出在哪
