### ISSUE TITLE
请问在kuboard中如何修改一个集群的名字

### ISSUE THREAD

**Issue by snakeysky** [eip-work/kuboard-press#261]
由于搭建时没注意，集群的名字没有自定义，但是找不到kuboard里哪里能修改集群的名字。
注意，是集群的名字，不是机器名，服务名。是显示在kuboard首页-<集群名>-<名称空间>这一排里的集群名。
谢谢。

**Comment by shaohq** [comment]
这个名字不能修改，相当于集群在 Kuboard 里的 ID，如果要修改，请删除后重新导入。
