### ISSUE TITLE
可以显示所有namespace的pod吗？

### ISSUE THREAD

**Issue by jibill** [eip-work/kuboard-press#267]
好像只能按namespace来查看pod，感觉不大方便，namespace多了，都不知道哪个服务在哪个namespace里，想搜索也不找不到地方搜索。

**Comment by suyanhj** [comment]
这个我感觉可以加一个按命名空间去显示pod，因为有的集群里面可能会使用额外的控制器去管理pod，比如说argo rollout或者openkruise、openkruise等去管理pod，但这些额外的crd是做了deployment的增强功能，不属于原生deployment控制器，所以在kuborad中看不到，如果要看日志就需要在命令行用kubectl查看，比较麻烦，如果有pod直接显示，就能直接看日志也不用对那些额外的控制器做开发，属于比较便捷又简单的方式了

![image](https://github.com/user-attachments/assets/cc255ff9-fbbe-47c3-801a-368beda269c7)
