### ISSUE TITLE
【安全漏洞】存在用户枚举漏洞

### ISSUE THREAD

**Issue by ilsl1007** [eip-work/kuboard-press#297]
@shaohq 

**我们将 Kuboard 部署到客户服务器，以下是安全机构检测到的安全漏洞。请问下大佬，如果用户名或密码匹配不上，则统一响应为用户名或密码错误。开启双因子认证后也是此问题。**

## 漏洞及风险描述
>   **在平台的登录页面，利用登陆时输入系统存在的用户名错误密码和不存在的用户名错误密码，返回不同的报错信息可枚举出系统中存在的账号信息。**

## 相关截图
<center class = "half">
<img width="47%" alt="1" src="https://user-images.githubusercontent.com/26399744/147056882-0b24707f-bee1-49ed-81f7-58e1be7f34ab.png" align="left"><img width="47%" alt="2" src="https://user-images.githubusercontent.com/26399744/147056928-02dd26a0-eb58-4400-855f-4abe8a028b48.png" align="right">
</center>    

## 通过 BurpSuite 工具进行用户的枚举
![image](https://user-images.githubusercontent.com/26399744/147057659-4205a482-50aa-4bbc-aa14-436e365562cf.png)

## 处置建议

**1. 建议修改网站登录页面的判断回显信息；
2. 设置在一段时间内的同一用户尝试登陆次数和登陆者的IP的阈值，超过一定次数进行锁定（用户登陆次数的话有可能会恶意登录锁定帐号的风险）；
3. 建议应用系统增加除用户名/密码以外的身份鉴别技术，如验证码/令牌、生物鉴别方式等双因素认证方式，增强身份鉴别的安全力度。**

**Comment by shaohq** [comment]
感谢您的反馈，会在下一个版本里修订，预计1月10日发布。

**Comment by shaohq** [comment]
已在 v3.3.0.4 版本中修订
