### ISSUE TITLE
kuboard-v3 无法启动

### ISSUE THREAD

**Issue by meilihao** [eip-work/kuboard-press#328]
环境是aliyun ecs + ubuntu 20.04，用kubekey部署的单机k8s v1.24.0

> 已知kuboard-v3最高兼容v1.23， 但手边只有k8s v1.24.0

```bash
# kubectl apply -f https://addons.kuboard.cn/kuboard/kuboard-v3.yaml
# kubectl get pods -n kuboard
NAME                          READY   STATUS             RESTARTS         AGE
kuboard-etcd-nzc74            1/1     Running            0                32m
kuboard-v3-7485cd46c8-5fm6p   0/1     CrashLoopBackOff   11 (2m20s ago)   32m
# kubectl logs -n kuboard  kuboard-v3-7485cd46c8-5fm6p
生成 KUBOARD_SSO_CLIENT_SECRET: 0e219c591253699ab96123d3
设置 KuboardAdmin 的默认密码（仅第一次启动时设置） Kuboard123
KUBOARD_ENDPOINT http://192.168.0.43:30080
eyJhbGciOiJSUzI1NiIsImtpZCI6IjB6TDhoTHZMTlJlSWI3QUFQVzhvSWJCbnJoM3JCamtXRGZGQ0l0Z1MzT1EifQ.eyJhdWQiOlsiaHR0cHM6Ly9rdWJlcm5ldGVzLmRlZmF1bHQuc3ZjLmNsdXN0ZXIubG9jYWwiXSwiZXhwIjoxNjg0NDAxNTcyLCJpYXQiOjE2NTI4NjU1NzIsImlzcyI6Imh0dHBzOi8va3ViZXJuZXRlcy5kZWZhdWx0LnN2Yy5jbHVzdGVyLmxvY2FsIiwia3ViZXJuZXRlcy5pbyI6eyJuYW1lc3BhY2UiOiJrdWJvYXJkIiwicG9kIjp7Im5hbWUiOiJrdWJvYXJkLXYzLTc0ODVjZDQ2YzgtNWZtNnAiLCJ1aWQiOiIyYzY5Yjk1Zi1kZGE4LTQzNjUtODQyNy0xM2RhZjAwNGIxMjEifSwic2VydmljZWFjY291bnQiOnsibmFtZSI6Imt1Ym9hcmQtYm9vc3RyYXAiLCJ1aWQiOiJmNjJmNjRiMC03MGUxLTQ2NDAtOGMxOS0wOWE5Y2NiMTcyNWMifSwid2FybmFmdGVyIjoxNjUyODY5MTc5fSwibmJmIjoxNjUyODY1NTcyLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3Vib2FyZDprdWJvYXJkLWJvb3N0cmFwIn0.g_cI15XzFz_4suBeXpDpaPSM-gmMWCVnDNh3tBUGNnRCxMZR4hIaNKzpQDexrF4Zc9xrpiYQ2Px1Be82cv3ZmWBPC3tyR2K_p3FWimlzWjWvqFoBcUWlNbtF85S4cWAI7PhcKnIBz4XrI8w2oq0SCVtYE7ReOR2FV43uFhXbd0Bdkqry6k-Iqak4csmdNbOUuZ61EeKhwmvKsGQ24XrkwbdoFz2xKg2Pz-mCUhgDcmjKPlBB720c_6Xnq2hg2xzob7_aU5iqEIVSraMEBJYFzZfwfxLROOW2qGIIgT-wzQeorHBM4ZtQ5YDh8LwVzGsbRBwehLsJSg-8RRmrLST-dA
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   115  100   115    0     0   3382      0 --:--:-- --:--:-- --:--:--  3484
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   115  100   115    0     0   6764      0 --:--:-- --:--:-- --:--:--  7666
[{
  "kind": "NodeList",
  "apiVersion": "v1",
  "metadata": {
    "resourceVersion": "1490541"
  },
  "items": []
},{
  "kind": "NodeList",
  "apiVersion": "v1",
  "metadata": {
    "resourceVersion": "1490541"
  },
  "items": []
}]



start kuboard-agent-server
当前 Kuboard 在 K8S 中运行，etcd 独立部署
启动内置的 QuestDB

  ___                  _   ____  ____
 / _ \ _   _  ___  ___| |_|  _ \| __ )
| | | | | | |/ _ \/ __| __| | | |  _ \
| |_| | |_| |  __/\__ \ |_| |_| | |_) |
 \__\_\\__,_|\___||___/\__|____/|____/
                        www.questdb.io

/questdb/bin/questdb.sh: line 66: ps: command not found
JAVA: /questdb/bin/java
QuestDB server 6.0.4
Copyright (C) 2014-2022, all rights reserved.

认证模块：使用本地用户库
启动 kuboard-sso
设置日志级别为 info
time="2022-05-18T09:48:28Z" level=info msg="config using log level: info"
time="2022-05-18T09:48:28Z" level=info msg="config issuer: http://192.168.0.43:30080/sso"
time="2022-05-18T09:48:28Z" level=info msg="config storage: etcd"
time="2022-05-18T09:48:28Z" level=info msg="config static client: KuboardApp"
time="2022-05-18T09:48:28Z" level=info msg="config connector: default"
time="2022-05-18T09:48:28Z" level=info msg="config skipping approval screen"
time="2022-05-18T09:48:28Z" level=info msg="config signing keys expire after: 6h0m0s"
time="2022-05-18T09:48:28Z" level=info msg="config id tokens valid for: 168h0m0s"
time="2022-05-18T09:48:28Z" level=info msg="config device requests valid for: 5m0s"
设置日志级别为 info
[LOG] 2022/05/18 - 17:48:31.698   | /common/etcd.client_config                                    24 |  info | KUBOARD_ETCD_ENDPOINTS=[]
[LOG] 2022/05/18 - 17:48:31.698   | /common/etcd.client_config                                    52 |  info | {[] 0s 1s 0s 0s 0 0 <nil>   false [] <nil> <nil> <nil> false}
[LOG] 2022/05/18 - 17:48:31.699   | /initializekuboard.InitializeEtcd                             39 |  info | 初始化 ./init-etcd-scripts/audit-policy-once.yaml
{"level":"warn","ts":"2022-05-18T17:48:33.589+0800","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-c197ff34-5bba-4081-b4c3-91fbd3179457/","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp: missing address\""}
failed to initialize server: server: failed to list connector objects from storage: context deadline exceeded
```

**Comment by cyscg** [comment]
解决了么？是不是1.24兼容问题，我的也是1.24

**Comment by meilihao** [comment]
没解决, 等兼容1.24后再试试

**Comment by Garibel-Lee** [comment]
同 kubeadm 部署1.24  宿主机 exsi6.7虚拟机 debian11 * 5 ，   三主两从  ，ku 拉不起来端口访问不到  卡住   //:80/kuboard-resources/version.json

**Comment by Zephery** [comment]
update，有大佬解决一下么?

**Comment by Garibel-Lee** [comment]
需要使用 storage class 方式创建

**Comment by Garibel-Lee** [comment]
---
apiVersion: v1
kind: PersistentVolume
metadata:
  finalizers:
    - kubernetes.io/pv-protection
  name: nfs-pv-nfs
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 200Gi
  mountOptions: []
  nfs:
    path: /volume1/nfs01/k8s
    server: 192.168.50.110
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storageclass-provisioner
  volumeMode: Filesystem

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
    - kubernetes.io/pvc-protection
  name: nfs-pvc-nfs
  namespace: kube-system
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: nfs-storageclass-provisioner
  volumeMode: Filesystem
  volumeName: nfs-pv-nfs

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: eip-nfs-client-provisioner
  namespace: kube-system
  resourceVersion: '244059'

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eip-nfs-client-provisioner-runner
  resourceVersion: '244060'
rules:
  - apiGroups:
      - ''
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - create
      - update
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: eip-run-nfs-client-provisioner
  resourceVersion: '244061'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: eip-nfs-client-provisioner-runner
subjects:
  - kind: ServiceAccount
    name: eip-nfs-client-provisioner
    namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: eip-leader-locking-nfs-client-provisioner
  namespace: kube-system
  resourceVersion: '244062'
rules:
  - apiGroups:
      - ''
    resources:
      - endpoints
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: eip-leader-locking-nfs-client-provisioner
  namespace: kube-system
  resourceVersion: '244063'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: eip-leader-locking-nfs-client-provisioner
subjects:
  - kind: ServiceAccount
    name: eip-nfs-client-provisioner
    namespace: kube-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: eip-nfs-nfs
  name: eip-nfs-nfs
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eip-nfs-nfs
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: eip-nfs-nfs
    spec:
      containers:
        - env:
            - name: PROVISIONER_NAME
              value: nfs-nfs
            - name: NFS_SERVER
              value: 192.168.50.110
            - name: NFS_PATH
              value: /volume1/nfs01/k8s
          image: >-
            swr.cn-east-2.myhuaweicloud.com/kuboard-dependency/nfs-subdir-external-provisioner:v4.0.2
          name: nfs-client-provisioner
          volumeMounts:
            - mountPath: /persistentvolumes
              name: nfs-client-root
      serviceAccountName: eip-nfs-client-provisioner
      volumes:
        - name: nfs-client-root
          persistentVolumeClaim:
            claimName: nfs-pvc-nfs

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    k8s.kuboard.cn/storageType: nfs_client_provisioner
  name: nfs
mountOptions: []
parameters:
  archiveOnDelete: 'false'
provisioner: nfs-nfs
reclaimPolicy: Retain
volumeBindingMode: Immediate

**Comment by Garibel-Lee** [comment]
用的nfs storageclass方案，kuboard-v3里里面sc name用nfs

**Comment by veris4crm** [comment]
我用“方法二：使用 StorageClass [[提供持久化”是可以安装成功的，官网文档地址：](https://kuboard.cn/install/v3/install-in-k8s.html#%E6%96%B9%E6%B3%95%E4%BA%8C-%E4%BD%BF%E7%94%A8-storageclass-%E6%8F%90%E4%BE%9B%E6%8C%81%E4%B9%85%E5
![1656493498551](https://user-images.githubusercontent.com/26327972/176397998-b7063296-50ea-4a44-8ac4-3c4cf2101fa3.jpg)
%8C%96)

**Comment by littlegreyzhang** [comment]
KUBOARD_ENDPOINT

**Comment by alexQi** [comment]
docker部署有同样的问题
`{"level":"warn","ts":"2022-10-18T10:24:33.400+0800","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-70ede7d6-5c6d-4bf2-a739-3f9f28a9da57/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
failed to initialize server: server: failed to list connector objects from storage: context deadline exceeded
{"level":"info","ts":"2022-10-18T10:25:34.800+0800","caller":"etcdserver/server.go:451","msg":"recovered v2 store from snapshot","snapshot-index":1220122,"snapshot-size":"8.9 kB"}`

**Comment by 2581543189** [comment]
> 不需要用方案二，你们把两个配置文件下载下来对比下就知道了，主要是访问问题，所以把方案一的配置文件中`KUBOARD_SERVER_NODE_PORT`配置项改成`KUBOARD_ENDPOINT`就可以了 如下： `KUBOARD_SERVER_NODE_PORT: '30080'` ===> `KUBOARD_ENDPOINT: 'http://your-node-ip-address:30080'`

改这个配置确实可以，万分感谢！

**Comment by liangsqrt** [comment]
> 不需要用方案二，你们把两个配置文件下载下来对比下就知道了，主要是访问问题，所以把方案一的配置文件中`KUBOARD_SERVER_NODE_PORT`配置项改成`KUBOARD_ENDPOINT`就可以了 如下： `KUBOARD_SERVER_NODE_PORT: '30080'` ===> `KUBOARD_ENDPOINT: 'http://your-node-ip-address:30080'`

实测可以

**Comment by meilihao** [comment]
看到kuboard已兼容到k8s v1.26

**Comment by craone** [comment]
> KUBOARD_SERVER_NODE_PORT: '30080' ===> KUBOARD_ENDPOINT: 'http://your-node-ip-address:30080' 改这个后还是不行,提示是127.0.0.1:2379连不上,用sealos装的k8s

再加一个
`KUBOARD_ETCD_ENDPOINTS: your-node-ip-address:2386`

**Comment by non-native** [comment]
> 不需要用方案二，你们把两个配置文件下载下来对比下就知道了，主要是访问问题，所以把方案一的配置文件中`KUBOARD_SERVER_NODE_PORT`配置项改成`KUBOARD_ENDPOINT`就可以了 如下： `KUBOARD_SERVER_NODE_PORT: '30080'` ===> `KUBOARD_ENDPOINT: 'http://your-node-ip-address:30080'`

点赞
