### ISSUE TITLE
是否提供HTTP-API进行服务信息查询、管理（如pod、宿主机信息查看、缩容、扩容等高频功能操作）

### ISSUE THREAD

**Issue by zengxiaoliang** [eip-work/kuboard-press#364]
各位大佬，
翻了下文档和之前的iisues ,没有找到介绍如何调用HTTP-API 进行常规的操作，想问下大佬些是此平台是否支持

**Comment by zengxiaoliang** [comment]
-H "content-type: application/json" \
-H "Cookie: KuboardUsername=demo;KuboardAccessKey=3ywz7yztic8e.drxh5ak4jsnf5ird2cyp4n8rcy7r7ce6" \
"https://demo.kuboard.cn/kuboard-api/cluster/k8s-19/kind/KuboardAccessGate"
{"kind":"KuboardErrorResponse","metadata":{"name":"","cluster":""},"code":403,"details":{"Kind":"","Cluster":"","Name":""},"message":"User demo not allowed on KuboardAccessGate.LIST","reason":"demo no privilige"}%

尝试了这个，发现也不行

**Comment by zengxiaoliang** [comment]
F12  抓到接口  可以使用

**Comment by llsydn** [comment]
> F12 抓到接口 可以使用

但是调用接口，需要token的，你怎么处理token这个？

**Comment by llsydn** [comment]
> -H "content-type: application/json" -H "Cookie: KuboardUsername=demo;KuboardAccessKey=3ywz7yztic8e.drxh5ak4jsnf5ird2cyp4n8rcy7r7ce6" "https://demo.kuboard.cn/kuboard-api/cluster/k8s-19/kind/KuboardAccessGate" {"kind":"KuboardErrorResponse","metadata":{"name":"","cluster":""},"code":403,"details":{"Kind":"","Cluster":"","Name":""},"message":"User demo not allowed on KuboardAccessGate.LIST","reason":"demo no privilige"}%
> 
> 尝试了这个，发现也不行

这个是可以的
