### ISSUE TITLE
kuboard-etcd 磁盘占用达到2G导致etcd无法访问

### ISSUE THREAD

**Issue by Fluxay-666** [eip-work/kuboard-press#386]
`du -h -d 0 /usr/share/kuboard/etcd/`
`2.5G	/usr/share/kuboard/etcd/`
我想手动压缩etcd数据发现etcd没有办法正常访问
![image](https://user-images.githubusercontent.com/51819781/210026711-cebec6e6-4263-4753-b6e5-0a5506293259.png)

**Comment by Fluxay-666** [comment]
已解决,kuboard-etcd默认端口是2381,端口用错了
`ETCDCTL_API=3 etcdctl --endpoints="http://127.0.0.1:2381" --write-out=table endpoint status`

`etcdctl --endpoints="http://127.0.0.1:2381" snapshot save /data/backup.db`

`ETCDCTL_API=3 etcdctl --endpoints="http://127.0.0.1:2381" compact $(ETCDCTL_API=3 etcdctl --endpoints="http://127.0.0.1:2381" endpoint status --write-out="json" | egrep -o '"revision":[0-9]*' | egrep -o '[0-9].*')`

`ETCDCTL_API=3 etcdctl --endpoints="http://127.0.0.1:2381" defrag`

`ETCDCTL_API=3 etcdctl --endpoints=http://127.0.0.1:2381 alarm disarm`

**Comment by xianhuadezhuren** [comment]
> 已解决,kuboard-etcd默认端口是2381,端口用错了 `ETCDCTL_API=3 etcdctl --endpoints="http://127.0.0.1:2381" --write-out=table endpoint status`
> 
> `etcdctl --endpoints="http://127.0.0.1:2381" snapshot save /data/backup.db`
> 
> `ETCDCTL_API=3 etcdctl --endpoints="http://127.0.0.1:2381" compact $(ETCDCTL_API=3 etcdctl --endpoints="http://127.0.0.1:2381" endpoint status --write-out="json" | egrep -o '"revision":[0-9]*' | egrep -o '[0-9].*')`
> 
> `ETCDCTL_API=3 etcdctl --endpoints="http://127.0.0.1:2381" defrag`
> 
> `ETCDCTL_API=3 etcdctl --endpoints=http://127.0.0.1:2381 alarm disarm`

直接登录不了，大佬怎么解决的啊

**Comment by xianhuadezhuren** [comment]
[root@k8s-master ~]# ETCDCTL_API=3 etcdctl --endpoints="http://127.0.0.1:2381" --write-out=table endpoint status
{"level":"warn","ts":"2024-05-10T17:13:47.952+0800","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"passthrough:///http://127.0.0.1:2381","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: connection closed"}
Failed to get the status of endpoint http://127.0.0.1:2381 (context deadline exceeded)
+----------+----+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
| ENDPOINT | ID | VERSION | DB SIZE | IS LEADER | IS LEARNER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |
+----------+----+---------+---------+-----------+------------+-----------+------------+--------------------+--------+
+----------+----+---------+---------+-----------+------------+-----------+------------+--------------------+--------+

**Comment by Fluxay-666** [comment]
@xianhuadezhuren 看看yaml文件里的端口对吗
<img width="620" alt="image" src="https://github.com/eip-work/kuboard-press/assets/51819781/9333ead4-41a7-42b6-83b8-d09bfd44865e">

**Comment by Fluxay-666** [comment]
> `du -h -d 0 /usr/share/kuboard/etcd/` `2.5G /usr/share/kuboard/etcd/` 我想手动压缩etcd数据发现etcd没有办法正常访问 ![图像](https://user-images.githubusercontent.com/51819781/210026711-cebec6e6-4263-4753-b6e5-0a5506293259.png)

使用命令压缩历史之前需注意etcdserver监听地址
![image](https://github.com/eip-work/kuboard-press/assets/51819781/9b7efd60-ac74-4bbf-916a-c62d242cc33e)

**Comment by nangongchengfeng** [comment]
{"level":"info","ts":"2024-06-19T07:08:05.047Z","caller":"embed/etcd.go:245","msg":"now serving peer/client/metrics","local-member-id":"18793330f04e826a","initial-advertise-peer-urls":["http://192.168.102.30:2382"],"listen-peer-urls":["http://192.168.102.30:2382"],"advertise-client-urls":["http://192.168.102.30:2381"],"listen-client-urls":["http://192.168.102.30:2381"],"listen-metrics-urls":[]}


![image](https://github.com/eip-work/kuboard-press/assets/46562911/42ac0ed9-8547-4ecf-8fd5-d95fed21fff9)

我使用 2381 和  2382 都不行。主要是现在etcd起不来，怎么才能连接内部清理数据？

![image](https://github.com/eip-work/kuboard-press/assets/46562911/5eb7800c-6313-451b-9811-df4bf7f35776)

**Comment by Fluxay-666** [comment]
> {“level”：“info”，“ts”：“2024-06-19T07：08：05.047Z”，“caller”：“embed/etcd.go：245”，“msg”：“现在服务peer/client/metrics”，“local-member-id”：“18793330f04e826a”，“initial-advertise-peer-urls”：[“http://192.168.102.30:2382”]，“listen-peer-urls”：[“http://192.168.102.30:2382”]，“advertise-client-urls”：[“http://192.168.102.30:2381”]，“listen-client-urls”：[“http://192.168.102.30:2381”]，“listen-metrics-urls”：[]}
> 
> ![图像](https://private-user-images.githubusercontent.com/46562911/340962998-42ac0ed9-8547-4ecf-8fd5-d95fed21fff9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODE2NTksIm5iZiI6MTcxODc4MTM1OSwicGF0aCI6Ii80NjU2MjkxMS8zNDA5NjI5OTgtNDJhYzBlZDktODU0Ny00ZWNmLThmZDUtZDk1ZmVkMjFmZmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA3MTU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhM2U0YTA5ODM2ZjFlNmVmMGZiN2RiYjhjZjY4MDE5MWM3Zjk4NjBlY2MyMmZkZjczYjY3OGE3NzZjZDIzNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A7U_pr1JnqRQm6PcY8qO89orBgCJvCqPOtW-FTxqlBk)
> 
> 我使用 2381 和 2382 都不行。主要是现在etcd起不来，怎么才能连接内部清理数据？
> 
> ![图像](https://private-user-images.githubusercontent.com/46562911/340964135-5eb7800c-6313-451b-9811-df4bf7f35776.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODE2NTksIm5iZiI6MTcxODc4MTM1OSwicGF0aCI6Ii80NjU2MjkxMS8zNDA5NjQxMzUtNWViNzgwMGMtNjMxMy00NTFiLTk4MTEtZGY0YmY3ZjM1Nzc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA3MTU1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmY2U5ZWQ1MGE4ZTFkNzkzM2I0MTg3ZWI5OTk0YzViOWQ0NjA4MzdlNmVmYjY0OTI0MDU4YmRjZGI2YjU4M2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zYHZ01eqjuJFP48q4BFXzjmNVXhYk8taJEu0pGNKDl8)

我看你监听的事192的IP，用这个试试。
是在k8s集群吗

**Comment by nangongchengfeng** [comment]
哎，不行，感觉还是etcd有问题导致。没起来，所以连不上。

 ETCDCTL_API=3 ./etcdctl  --endpoints="http://192.168.102.30:2381" --write-out=table endpoint status
![image](https://github.com/eip-work/kuboard-press/assets/46562911/5f56b061-1181-447d-afc4-616204b3fffd)
成功访问一次，后续访问失败，这是运气吗（狗头保命）
![image](https://github.com/eip-work/kuboard-press/assets/46562911/f37eccdb-05e1-4f78-845d-fb81f6440ec3)

**Comment by Fluxay-666** [comment]
> 哎，不行，感觉还是etcd有问题导致。没起来，所以连不上。
> 
> ETCDCTL_API=3 ./etcdctl --endpoints="http://192.168.102.30:2381" --write-out=table endpoint status ![image](https://private-user-images.githubusercontent.com/46562911/340976628-5f56b061-1181-447d-afc4-616204b3fffd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODM2NDUsIm5iZiI6MTcxODc4MzM0NSwicGF0aCI6Ii80NjU2MjkxMS8zNDA5NzY2MjgtNWY1NmIwNjEtMTE4MS00NDdkLWFmYzQtNjE2MjA0YjNmZmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA3NDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2OWJlNzMyODIxZTc3ZWI4MDU2MDMxNmI3ZWFlN2Y4YTRhYWI2ZDAzMDRmZjJjMWViMTY3YzNjN2U3OTAwZTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vYcCcFjc7ceGtMUFRLnIsJj8OC5mFjA90d25HBBDEm8) 成功访问一次，后续访问失败，这是运气吗（狗头保命） ![image](https://private-user-images.githubusercontent.com/46562911/340976858-f37eccdb-05e1-4f78-845d-fb81f6440ec3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3ODM2NDUsIm5iZiI6MTcxODc4MzM0NSwicGF0aCI6Ii80NjU2MjkxMS8zNDA5NzY4NTgtZjM3ZWNjZGItMDVlMS00Zjc4LTg0NWQtZmI4MWY2NDQwZWMzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDA3NDkwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxOTcyYzIwYzM0MGIzMWM0ZjliYWE3ZDcxNWNiOGIyNDE5N2JlNTNiNDA4ZWU1ODQwZjUxZDZmZDE0YzA4ODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ujXrAl59DUBTyQzUg92rf1q0QZZDU2qBnW1j-G5z7og)

是在k8s集群里吗？他会有健康检测，我把健康检测注释之后就可以了

**Comment by xianhuadezhuren** [comment]
> @xianhuadezhuren 看看yaml文件里的端口对吗 <img alt="image" width="620" src="https://private-user-images.githubusercontent.com/51819781/334712634-9333ead4-41a7-42b6-83b8-d09bfd44865e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4NzE0NTEsIm5iZiI6MTcxODg3MTE1MSwicGF0aCI6Ii81MTgxOTc4MS8zMzQ3MTI2MzQtOTMzM2VhZDQtNDFhNy00MmI2LTgzYjgtZDA5YmZkNDQ4NjVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIwVDA4MTIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkNDc2MWQ4ODQwMmM1MTcwMzE3ZTBhNzQwYjAyYWJjOGZmMWJiNDBmMjQwOGNmNzY4YjI0ODkyOTRiNDJlOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.YKW51QL-kHl-iNM_BuyPCM3W48LTFxqOZ41sfhKhg_s">

嗯嗯   可以了   感谢大佬
