### ISSUE TITLE
sso用户无法跳转到集群中

### ISSUE THREAD

**Issue by Quinlan0516** [eip-work/kuboard-press#474]
![image](https://github.com/eip-work/kuboard-press/assets/44350701/25395f73-07a1-43fb-abdf-fc8fabf57254)
点击赋权空间后，页面无法完成跳转，又回到这个页面，
这个权限在之前是好使的，就是突然不能用了，集群也突然变为了存在问题
大概排查是/kuboard-api/selfInfo这个接口返回的用户状态有问题，但不知道后续应该怎样处理，
![image](https://github.com/eip-work/kuboard-press/assets/44350701/44c995fc-fa8e-4614-a950-8d94a592c80c)

PS：使用的是腾讯云TKE集群

**Comment by Gourds** [comment]
咋解决的 @Quinlan0516
