### ISSUE TITLE
kuboard etcd启动失败

### ISSUE THREAD

**Issue by qinquanliuxiang** [eip-work/kuboard-press#493]
安装kuboard单节点的k3s集群etcd可以成功启动，3节点etcd启动失败
报错：
parse error: Invalid escape at line 1, column 2279
2024-01-12 11:17:11.890462 E | etcdmain: error verifying flags, 'new' is not a valid flag. See 'etcd --help'.
这是什么原因？

**Comment by FreeBoys** [comment]
同样的问题

**Comment by whhya** [comment]
请问是否有解决方案


> 安装kuboard单节点的k3s集群etcd可以成功启动，3节点etcd启动失败 报错： parse error: Invalid escape at line 1, column 2279 2024-01-12 11:17:11.890462 E | etcdmain: error verifying flags, 'new' is not a valid flag. See 'etcd --help'. 这是什么原因？
