### ISSUE TITLE
高CPU占用率

### ISSUE THREAD

**Issue by AiSY-Yang** [eip-work/kuboard-press#509]
![image](https://github.com/eip-work/kuboard-press/assets/20870087/d0f43ef5-00aa-4abd-912b-f98707146157)

![image](https://github.com/eip-work/kuboard-press/assets/20870087/48bd06e9-7c5e-4d2a-a224-ab6751db8afb)

都干了点啥 直接把我服务器干死了

**Comment by AiSY-Yang** [comment]
我知道了,是我的服务器太拉了,不过这玩意要一个多G内存也有点多了吧,2C2G跑个UI就占满了

**Comment by myysophia** [comment]
被挖矿了  老哥

**Comment by AiSY-Yang** [comment]
> 被挖矿了 老哥

不是的 真的是吃资源
我现在不跑在服务器上了 在本地电脑上运行kuboard管理云服务器  docker desktop显示占用10%的CPU
我的处理器是AMD Ryzen 7 5800H with Radeon Graphics            3.20 GHz  8C16线程

**Comment by myysophia** [comment]
> > 被挖矿了 老哥
> 
> 不是的 真的是吃资源 我现在不跑在服务器上了 在本地电脑上运行kuboard管理云服务器 docker desktop显示占用10%的CPU 我的处理器是AMD Ryzen 7 5800H with Radeon Graphics 3.20 GHz 8C16线程

这个镜像是干什么的？jocker0314/alpine:ssl

**Comment by AiSY-Yang** [comment]
> > > 被挖矿了 老哥
> > 
> > 
> > 不是的 真的是吃资源 我现在不跑在服务器上了 在本地电脑上运行kuboard管理云服务器 docker desktop显示占用10%的CPU 我的处理器是AMD Ryzen 7 5800H with Radeon Graphics 3.20 GHz 8C16线程
> 
> 这个镜像是干什么的？jocker0314/alpine:ssl
我这里没有这个镜像啊 老哥是不是开了多个窗口看串了
