### ISSUE TITLE
查看监控结果跳转报错

### ISSUE THREAD

**Issue by A11Might** [eip-work/kuboard-press#550]
按照文档成功安装资源层监控套件，在查看监控结果时报错，如下：
```
调用 grafana 接口失败
Error: Request failed with status code 504
```
kubernetes版本：1.19.4
kuboard版本：3.1.1.9
agent版本：3.5.1
监控套件版本：3.1.8

**Comment by stelin** [comment]
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "error trying to reach service: proxy error from 127.0.0.1:6443 while dialing 10.42.4.113:3000, code 502: 502 Bad Gateway",
  "reason": "ServiceUnavailable",
  "code": 503
}
怎么
