### ISSUE TITLE
kuboard 没办法启动，第一次启动成功，登录就报异常，etcd查看正常

### ISSUE THREAD

**Issue by dazhu6666** [eip-work/kuboard-press#564]
设置日志级别为 info
[LOG] 2024/12/18 - 20:33:02.553   | /common/etcd.client_config                                    24 |  info | KUBOARD_ETCD_ENDPOINTS=[127.0.0.1:2379]
[LOG] 2024/12/18 - 20:33:02.553   | /common/etcd.client_config                                    52 |  info | {[127.0.0.1:2379] 0s 1s 0s 0s 0 0 <nil>   false [] <nil> <nil> <nil> false}
[LOG] 2024/12/18 - 20:33:02.554   | /initializekuboard.InitializeEtcd                             39 |  info | 初始化 ./init-etcd-scripts/audit-policy-once.yaml
{"level":"warn","ts":"2024-12-18T20:33:04.317+0800","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker failed","target":"endpoint://client-c157a25d-7202-4ad8-bb1b-9a6db34b9c8a/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = context deadline exceeded"}
failed to initialize server: server: failed to list connector objects from storage: context deadline exceeded
{"level":"info","ts":"2024-12-18T20:33:17.765+0800","caller":"etcdserver/server.go:469","msg":"recovered v3 backend from snapshot","backend-size-bytes":1824497664,"backend-size":"1.8 GB","backend-size-in-use-bytes":1824477184,"backend-size-in-use":"1.8 GB"}
{"level":"info","ts":"2024-12-18T20:33:17.832+0800","caller":"etcdserver/raft.go:536","msg":"restarting local member","cluster-id":"f9f44c4ba0e96dd8","local-member-id":"59a9c584ea2c3f35","commit-index":5164798}
{"level":"info","ts":"2024-12-18T20:33:17.833+0800","caller":"raft/raft.go:1530","msg":"59a9c584ea2c3f35 switched to configuration voters=(6460912315094810421)"}
{"level":"info","ts":"2024-12-18T20:33:17.833+0800","caller":"raft/raft.go:700","msg":"59a9c584ea2c3f35 became follower at term 44"}
{"level":"info","ts":"2024-12-18T20:33:17.833+0800","caller":"raft/raft.go:383","msg":"newRaft 59a9c584ea2c3f35 [peers: [59a9c584ea2c3f35], term: 44, commit: 5164798, applied: 5160516, lastindex: 5164798, lastterm: 44]"}
{"level":"info","ts":"2024-12-18T20:33:17.833+0800","caller":"api/capability.go:76","msg":"enabled capabilities for version","cluster-version":"3.4"}
{"level":"info","ts":"2024-12-18T20:33:17.833+0800","caller":"membership/cluster.go:256","msg":"recovered/added member from store","cluster-id":"f9f44c4ba0e96dd8","local-member-id":"59a9c584ea2c3f35","recovered-remote-peer-id":"59a9c584ea2c3f35","recovered-remote-peer-urls":["http://0.0.0.0:2380"]}
{"level":"info","ts":"2024-12-18T20:33:17.833+0800","caller":"membership/cluster.go:269","msg":"set cluster version from store","cluster-version":"3.4"}
{"level":"warn","ts":"2024-12-18T20:33:17.835+0800","caller":"auth/store.go:1366","msg":"simple token is not cryptographically signed"}
{"level":"info","ts":"2024-12-18T20:33:40.038+0800","caller":"etcdserver/quota.go:98","msg":"enabled backend quota with default value","quota-name":"v3-applier","quota-size-bytes":2147483648,"quota-size":"2.1 GB"}
{"level":"info","ts":"2024-12-18T20:33:40.040+0800","caller":"etcdserver/server.go:790","msg":"starting etcd server","local-member-id":"59a9c584ea2c3f35","local-server-version":"3.4.14","cluster-id":"f9f44c4ba0e96dd8","cluster-version":"3.4"}
{"level":"info","ts":"2024-12-18T20:33:40.042+0800","caller":"embed/etcd.go:244","msg":"now serving peer/client/metrics","local-member-id":"59a9c584ea2c3f35","initial-advertise-peer-urls":["http://0.0.0.0:2380"],"listen-peer-urls":["http://0.0.0.0:2380"],"advertise-client-urls":["http://0.0.0.0:2379"],"listen-client-urls":["http://0.0.0.0:2379"],"listen-metrics-urls":[]}
{"level":"info","ts":"2024-12-18T20:33:40.043+0800","caller":"embed/etcd.go:579","msg":"serving peer traffic","address":"[::]:2380"}
{"level":"info","ts":"2024-12-18T20:33:40.042+0800","caller":"etcdserver/server.go:669","msg":"started as single-node; fast-forwarding election ticks","local-member-id":"59a9c584ea2c3f35","forward-ticks":9,"forward-duration":"900ms","election-ticks":10,"election-timeout":"1s"}
{"level":"info","ts":"2024-12-18T20:33:40.933+0800","caller":"raft/raft.go:923","msg":"59a9c584ea2c3f35 is starting a new election at term 44"}
{"level":"info","ts":"2024-12-18T20:33:40.933+0800","caller":"raft/raft.go:713","msg":"59a9c584ea2c3f35 became candidate at term 45"}
{"level":"info","ts":"2024-12-18T20:33:40.934+0800","caller":"raft/raft.go:824","msg":"59a9c584ea2c3f35 received MsgVoteResp from 59a9c584ea2c3f35 at term 45"}
{"level":"info","ts":"2024-12-18T20:33:40.934+0800","caller":"raft/raft.go:765","msg":"59a9c584ea2c3f35 became leader at term 45"}
{"level":"info","ts":"2024-12-18T20:33:40.934+0800","caller":"raft/node.go:325","msg":"raft.node: 59a9c584ea2c3f35 elected leader 59a9c584ea2c3f35 at term 45"}
{"level":"info","ts":"2024-12-18T20:33:40.934+0800","caller":"etcdserver/server.go:2037","msg":"published local member to cluster through raft","local-member-id":"59a9c584ea2c3f35","local-member-attributes":"{Name:kuboard-01 ClientURLs:[http://0.0.0.0:2379]}","request-path":"/0/members/59a9c584ea2c3f35/attributes","cluster-id":"f9f44c4ba0e96dd8","publish-timeout":"7s"}
{"level":"info","ts":"2024-12-18T20:33:40.935+0800","caller":"embed/serve.go:139","msg":"serving client traffic insecurely; this is strongly discouraged!","address":"[::]:2379"}
[LOG] 2024/12/18 - 20:33:40.944   | /initializekuboard.processEtcdObject                         122 |  info |  - 忽略对象：KuboardAuditPolicy GLOBAL/GLOBAL
[LOG] 2024/12/18 - 20:33:40.944   | /initializekuboard.InitializeEtcd                             39 |  info | 初始化 ./init-etcd-scripts/bran-settings-once.yaml
[LOG] 2024/12/18 - 20:33:40.949   | /initializekuboard.processEtcdObject                         122 |  info |  - 忽略对象：KuboardBrandSettings GLOBAL/KuboardBrandSettings
[LOG] 2024/12/18 - 20:33:40.949   | /initializekuboard.InitializeEtcd                             39 |  info | 初始化 ./init-etcd-scripts/import-cluster-once.yaml
[LOG] 2024/12/18 - 20:33:40.951   | /initializekuboard.processEtcdObject                         122 |  info |  - 忽略对象：KubernetesCluster default/default
[LOG] 2024/12/18 - 20:33:40.951   | /initializekuboard.processEtcdObject                         122 |  info |  - 忽略对象：KubernetesClusterToken default/kuboard-admin
[LOG] 2024/12/18 - 20:33:40.952   | /initializekuboard.processEtcdObject                         122 |  info |  - 忽略对象：KubernetesClusterToken default/kuboard-viewer
[LOG] 2024/12/18 - 20:33:40.952   | /initializekuboard.InitializeEtcd                             39 |  info | 初始化 ./init-etcd-scripts/login-policy-once.yaml
[LOG] 2024/12/18 - 20:33:40.954   | /initializekuboard.processEtcdObject                         122 |  info |  - 忽略对象：KuboardLoginPolicySettings GLOBAL/KuboardLoginPolicySettings
[LOG] 2024/12/18 - 20:33:40.954   | /initializekuboard.InitializeEtcd                             39 |  info | 初始化 ./init-etcd-scripts/roles.yaml
[LOG] 2024/12/18 - 20:33:40.956   | /initializekuboard.processEtcdObject                         124 |  info |  - 更新对象：KuboardAuthRole GLOBAL/administrator
[LOG] 2024/12/18 - 20:33:40.964   | /initializekuboard.processEtcdObject                         124 |  info |  - 更新对象：KuboardAuthRole GLOBAL/viewer
[LOG] 2024/12/18 - 20:33:40.969   | /initializekuboard.processEtcdObject                         124 |  info |  - 更新对象：KuboardAuthRole GLOBAL/authenticated
[LOG] 2024/12/18 - 20:33:40.975   | /initializekuboard.processEtcdObject                         124 |  info |  - 更新对象：KuboardAuthRole GLOBAL/anonymous
[LOG] 2024/12/18 - 20:33:40.980   | /initializekuboard.processEtcdObject                         124 |  info |  - 更新对象：KuboardAuthRole GLOBAL/sso-user
[LOG] 2024/12/18 - 20:33:40.983   | /initializekuboard.InitializeEtcd                             39 |  info | 初始化 ./init-etcd-scripts/user.yaml
[LOG] 2024/12/18 - 20:33:40.987   | /initializekuboard.processEtcdObject                         124 |  info |  - 更新对象：KuboardAuthUser GLOBAL/admin
[LOG] 2024/12/18 - 20:33:40.991   | /initializekuboard.processEtcdObject                         124 |  info |  - 更新对象：KuboardAuthGroup GLOBAL/administrators
[LOG] 2024/12/18 - 20:33:40.995   | /initializekuboard.processEtcdObject                         124 |  info |  - 更新对象：KuboardAuthUserInGroup GLOBAL/admin.administrators
[LOG] 2024/12/18 - 20:33:41.004   | /initializekuboard.processEtcdObject                         124 |  info |  - 更新对象：KuboardAuthGlobalRoleBinding GLOBAL/group.administrators.administrator
[LOG] 2024/12/18 - 20:33:41.008   | /login.AddLoginRoutes                                         28 | error | 认证模块初始化失败：Get "http://127.0.0.1:5556/sso/.well-known/openid-configuration": dial tcp 127.0.0.1:5556: connect: connection refused
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x48 pc=0xd73477]

goroutine 1 [running]:
github.com/coreos/go-oidc.(*Provider).Verifier(...)
	/usr/src/kuboard/third-party/go-oidc/verify.go:111
github.com/shaohq/kuboard/server/login.AddLoginRoutes(0xc000183860)
	/usr/src/kuboard/server/login/login.go:30 +0xf7
main.getRoutes()
	/usr/src/kuboard/server/kuboard-server.go:191 +0x345
main.main()
	/usr/src/kuboard/server/kuboard-server.go:65 +0x185

启动 kuboard-server 失败，此问题通常是因为 Etcd 未能及时启动或者连接不上，系统将在 15 秒后重新尝试：
  1. 如果您使用 docker run 的方式运行 Kuboard，请耐心等候一会儿或者执行 docker restart kuboard；
  2. 如果您将 Kuboard 安装在 Kubernetes 中，请检查 kuboard/kuboard-etcd 是否正常启动。

怎么能修复？？？

**Comment by dazhu6666** [comment]
[root@master70 ~]# kubectl get cs
Warning: v1 ComponentStatus is deprecated in v1.19+
NAME                 STATUS    MESSAGE                         ERROR
scheduler            Healthy   ok                              
controller-manager   Healthy   ok                              
etcd-0               Healthy   {"health":"true","reason":""}

**Comment by lnnt** [comment]
我也遇到了同样的问题 ，最后咋解决的呢
